-- The initial schema. Append-only: later changes go in new migrations (CLAUDE.md hard rule 7).
--
-- Conventions:
-- - Entity ids are UUIDv7 text, generated by the server.
-- - Money is INTEGER cents. Dates are ISO `YYYY-MM-DD` text; timestamps are UTC RFC 3339 text.
-- - Account codes are stored as entered after normalising (acct-core's `AccountCode`). They sort in
--   Rust, not SQL, because code order compares numeric segments numerically.
-- - `*_seq` columns name the `command_log` entry that created the row.
-- - Enum-like text columns are checked in Rust when they're read, so adding a variant later doesn't
--   need a table rebuild.

-- The practice itself. There is exactly one row.
CREATE TABLE practice (
    id          INTEGER PRIMARY KEY CHECK (id = 1),
    name        TEXT    NOT NULL,
    created_seq INTEGER NOT NULL
);

CREATE TABLE users (
    id            TEXT    PRIMARY KEY,
    username      TEXT    NOT NULL UNIQUE COLLATE NOCASE,
    display_name  TEXT    NOT NULL,
    password_hash TEXT    NOT NULL,
    role          TEXT    NOT NULL,
    active        INTEGER NOT NULL CHECK (active IN (0, 1)),
    created_seq   INTEGER NOT NULL
);

-- Login sessions. Not practice data, so these are written outside the command pipeline.
-- Only a hash of the cookie's token is kept.
CREATE TABLE sessions (
    token_hash TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL REFERENCES users (id),
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
);
CREATE INDEX sessions_user ON sessions (user_id);

-- Every accepted command, in order. `seq` is gapless because only the single writer connection
-- inserts here, inside the command's own transaction. `result` is the response the command gave,
-- returned again if the same `id` is resubmitted. `payload` is stored as the command's own
-- redacted form, so secrets such as passwords never land here.
CREATE TABLE command_log (
    seq            INTEGER PRIMARY KEY,
    id             TEXT    NOT NULL UNIQUE,
    kind           TEXT    NOT NULL,
    payload        TEXT    NOT NULL,
    result         TEXT    NOT NULL,
    user_id        TEXT    REFERENCES users (id),
    client_id      TEXT,
    client_year_id TEXT,
    at             TEXT    NOT NULL
);
CREATE INDEX command_log_client ON command_log (client_id, seq);

-- The practice master chart for each entity type. A client's chart starts as a copy of it.
CREATE TABLE master_charts (
    id          TEXT    PRIMARY KEY,
    entity_type TEXT    NOT NULL UNIQUE,
    name        TEXT    NOT NULL,
    created_seq INTEGER NOT NULL
);

CREATE TABLE master_chart_accounts (
    chart_id     TEXT    NOT NULL REFERENCES master_charts (id),
    code         TEXT    NOT NULL,
    name         TEXT    NOT NULL,
    account_type TEXT    NOT NULL,
    active       INTEGER NOT NULL CHECK (active IN (0, 1)),
    PRIMARY KEY (chart_id, code)
) WITHOUT ROWID;

-- Statement templates and mappings. A version's body never changes once written; editing one
-- writes a new version. Client-years pin the versions they use.
CREATE TABLE templates (
    id          TEXT    PRIMARY KEY,
    entity_type TEXT    NOT NULL,
    name        TEXT    NOT NULL,
    created_seq INTEGER NOT NULL
);

CREATE TABLE template_versions (
    id          TEXT    PRIMARY KEY,
    template_id TEXT    NOT NULL REFERENCES templates (id),
    version     INTEGER NOT NULL CHECK (version >= 1),
    body        TEXT    NOT NULL,
    created_seq INTEGER NOT NULL,
    UNIQUE (template_id, version)
);

CREATE TABLE mappings (
    id          TEXT    PRIMARY KEY,
    template_id TEXT    NOT NULL REFERENCES templates (id),
    name        TEXT    NOT NULL,
    created_seq INTEGER NOT NULL
);

CREATE TABLE mapping_versions (
    id          TEXT    PRIMARY KEY,
    mapping_id  TEXT    NOT NULL REFERENCES mappings (id),
    version     INTEGER NOT NULL CHECK (version >= 1),
    body        TEXT    NOT NULL,
    created_seq INTEGER NOT NULL,
    UNIQUE (mapping_id, version)
);

-- `retained_earnings` is the designated equity account P&L accounts close to at rollover.
-- `rounding_priority` is a JSON array of account codes (docs/domain.md, rounding).
CREATE TABLE clients (
    id                TEXT    PRIMARY KEY,
    name              TEXT    NOT NULL,
    entity_type       TEXT    NOT NULL,
    retained_earnings TEXT    NOT NULL,
    rounding_priority TEXT    NOT NULL,
    created_seq       INTEGER NOT NULL
);

-- A client's own chart.
CREATE TABLE accounts (
    client_id    TEXT    NOT NULL REFERENCES clients (id),
    code         TEXT    NOT NULL,
    name         TEXT    NOT NULL,
    account_type TEXT    NOT NULL,
    active       INTEGER NOT NULL CHECK (active IN (0, 1)),
    PRIMARY KEY (client_id, code)
) WITHOUT ROWID;

-- `books_source` is NULL until the year's first TB import or bank coding fixes it.
-- `status` is `open` or `finalised`.
CREATE TABLE client_years (
    id                 TEXT    PRIMARY KEY,
    client_id          TEXT    NOT NULL REFERENCES clients (id),
    start_date         TEXT    NOT NULL,
    end_date           TEXT    NOT NULL CHECK (end_date >= start_date),
    template_version_id TEXT   NOT NULL REFERENCES template_versions (id),
    mapping_version_id TEXT    NOT NULL REFERENCES mapping_versions (id),
    books_source       TEXT,
    status             TEXT    NOT NULL,
    created_seq        INTEGER NOT NULL,
    UNIQUE (client_id, start_date)
);

-- Posted journals never change. A correction is a new journal that reverses one, and a journal
-- can be reversed only once. `kind` is `manual`, `tb_import` and so on.
CREATE TABLE journals (
    id                  TEXT    PRIMARY KEY,
    client_year_id      TEXT    NOT NULL REFERENCES client_years (id),
    kind                TEXT    NOT NULL,
    date                TEXT    NOT NULL,
    narration           TEXT    NOT NULL,
    reverses_journal_id TEXT    UNIQUE REFERENCES journals (id),
    posted_seq          INTEGER NOT NULL
);
CREATE INDEX journals_year ON journals (client_year_id, date);

CREATE TABLE journal_lines (
    journal_id TEXT    NOT NULL REFERENCES journals (id),
    line_no    INTEGER NOT NULL CHECK (line_no >= 1),
    account    TEXT    NOT NULL,
    amount     INTEGER NOT NULL,
    PRIMARY KEY (journal_id, line_no)
) WITHOUT ROWID;

-- What was signed when a year was finalised: the TB, the pinned versions, the ReportDoc and a
-- SHA-256 of its JSON. Kept after a reopen, so every signed version stays on record.
-- Written from M5; the table exists now so the schema is complete.
CREATE TABLE snapshots (
    id                  TEXT    PRIMARY KEY,
    client_year_id      TEXT    NOT NULL REFERENCES client_years (id),
    tb                  TEXT    NOT NULL,
    template_version_id TEXT    NOT NULL REFERENCES template_versions (id),
    mapping_version_id  TEXT    NOT NULL REFERENCES mapping_versions (id),
    report_doc          TEXT    NOT NULL,
    report_sha256       TEXT    NOT NULL,
    finalised_seq       INTEGER NOT NULL,
    finalised_by        TEXT    NOT NULL REFERENCES users (id)
);
CREATE INDEX snapshots_year ON snapshots (client_year_id);
