// src/features/admin/managerDashboardUI.js
import { useAppStore } from '@/store/appStore.js';
import * as api from '@/services/apiService.js';
import * as uiUtils from '@/utils/uiUtils.js';

let siteSettings = {}; // Module-level cache for settings

/**
 * Renders the God User (Manager) Dashboard interface.
 */
export async function renderManagerDashboard() {
    const mainContent = document.getElementById('main-content');
    if (!mainContent) return;

    mainContent.innerHTML = `<div class="loading-spinner">Loading settings...</div>`;

    try {
        // Fetch the latest site settings from the API
        siteSettings = await api.getSiteSettings();
    } catch (error) {
        mainContent.innerHTML = `<div class="error-message"><h2>Could not load site settings.</h2><p>${error.message}</p></div>`;
        return;
    }

    // Use the getThemeControlsHTML function from uiUtils to generate the theme editor
    const themeControlsHTML = uiUtils.getThemeControlsHTML(siteSettings.themeVariables || {});

    const dashboardHTML = `
        <div class="dashboard-container">
            <h2>God Mode Dashboard</h2>

            <!-- Global Site Settings Section -->
            <section class="dashboard-section">
                <h3>Global Site Settings</h3>
                <form id="global-settings-form">
                    <div class="form-group">
                        <label for="website-name">Website Name</label>
                        <input type="text" id="website-name" name="websiteName" value="${siteSettings.websiteName || 'Mealmates'}">
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="button-primary">Save Site Name</button>
                    </div>
                </form>
            </section>

            <!-- Theme Customizer Section -->
            <section class="dashboard-section">
                ${themeControlsHTML}
            </section>

            <!-- We will add other sections like User Management here later -->
        </div>
    `;

    mainContent.innerHTML = dashboardHTML;
    attachManagerDashboardListeners();
}

/**
 * Attaches event listeners for the manager dashboard.
 */
function attachManagerDashboardListeners() {
    // Listener for the global settings form (Website Name)
    const globalSettingsForm = document.getElementById('global-settings-form');
    if (globalSettingsForm) {
        globalSettingsForm.addEventListener('submit', handleGlobalSettingsSave);
    }

    // Listener for the "Save Theme Settings" button generated by uiUtils
    const saveThemeBtn = document.getElementById('save-theme-settings');
    if (saveThemeBtn) {
        saveThemeBtn.addEventListener('click', handleThemeSettingsSave);
    }

    // Live-update listener for theme color pickers/sliders (event delegation)
    const dashboardContainer = document.querySelector('.dashboard-container');
    if (dashboardContainer) {
        dashboardContainer.addEventListener('input', (event) => {
            const target = event.target;
            // Check if the input is a theme control generated by getThemeControlsHTML
            if (target.matches('[data-css-var]')) {
                const cssVarName = target.dataset.cssVar;
                uiUtils.updateCssVariable(cssVarName, target.value);
            }
        });
    }
}

/**
 * Handles saving the global site settings (e.g., website name).
 * @param {Event} event
 */
async function handleGlobalSettingsSave(event) {
    event.preventDefault();
    const websiteName = document.getElementById('website-name').value;
    if (!websiteName) {
        alert('Website name cannot be empty.');
        return;
    }

    try {
        await api.updateSiteSettings({ websiteName: websiteName });
        // Also update the live site titles immediately
        uiUtils.updateSiteTitles(websiteName);
        uiUtils.showToast('Website name updated successfully!', 'success');
    } catch (error) {
        alert(`Error saving settings: ${error.message}`);
    }
}

/**
 * Handles saving the theme variables to the database.
 */
async function handleThemeSettingsSave() {
    const themeVariables = {};
    // Gather all current values from the theme control inputs
    document.querySelectorAll('[data-css-var]').forEach(input => {
        themeVariables[input.dataset.cssVar] = input.value;
    });

    try {
        await api.updateSiteSettings({ themeVariables: themeVariables });
        uiUtils.showToast('Theme settings saved successfully!', 'success');
    } catch (error) {
        alert(`Error saving theme: ${error.message}`);
    }
}