// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The response to an accepted command, returned again for a resubmitted `id`.
 */
export type Accepted = { seq: number, 
/**
 * The id of the entity the command created, if it created one.
 */
entity_id: string | null, };
