// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An account code: one or more ASCII alphanumeric segments separated by `.`, such as `200`,
 * `200.01`, `1100` or `A100`. Letters are stored uppercase.
 *
 * Codes sort segment by segment (see `docs/domain.md`): an all-digit segment compares as a number
 * and sorts before a segment containing letters, and a code that is a prefix of another sorts
 * first. So `200` < `200.01` < `1100`. Codes that differ only in leading zeros (`0200`, `200`)
 * are different codes; the one with fewer characters sorts first.
 */
export type AccountCode = string;
