// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { AccountType } from "./AccountType";

export type Account = { code: AccountCode, name: string, account_type: AccountType, active: boolean, };
