// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The JSON body of every error response.
 */
export type ApiError = { 
/**
 * A stable snake_case code the UI can switch on.
 */
code: string, 
/**
 * A sentence for people.
 */
message: string, 
/**
 * Structured specifics, such as each journal problem found. `null` if there are none.
 */
details: unknown, };
