// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAccounts } from "./AssetAccounts";
import type { DepreciationSettings } from "./DepreciationSettings";
import type { RateSource } from "./RateSource";

/**
 * One asset whose settings or accounts would change if the class's current defaults were
 * applied.
 */
export type ApplyDefaultsChange = { asset_id: string, name: string, rate_source: RateSource, settings_from: DepreciationSettings, settings_to: DepreciationSettings, accounts_from: AssetAccounts, accounts_to: AssetAccounts, };
