// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";

/**
 * The accounts an asset's journals post to. Copied from its class when it's created.
 */
export type AssetAccounts = { cost: AccountCode, accumulated: AccountCode, expense: AccountCode, gain_loss: AccountCode, };
