// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetView } from "./AssetView";
import type { AssetYear } from "./AssetYear";

/**
 * One asset's line in a year's register.
 */
export type AssetYearView = { asset: AssetView, movements: AssetYear, };
