// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAccounts } from "./AssetAccounts";
import type { DepreciationSettings } from "./DepreciationSettings";

export type AssetClassView = { id: string, entity_type: string, key: string, name: string, settings: DepreciationSettings, accounts: AssetAccounts, };
