// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScheduleBlock } from "./ScheduleBlock";

/**
 * The fixed asset schedule: one block per class, then a total block. Whole dollars.
 */
export type AssetSchedule = { title: string, blocks: Array<ScheduleBlock>, };
