// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAccounts } from "./AssetAccounts";
import type { DepreciationSettings } from "./DepreciationSettings";
import type { Disposal } from "./Disposal";
import type { Money } from "./Money";
import type { OpeningBalance } from "./OpeningBalance";
import type { RateSource } from "./RateSource";

/**
 * One asset in a year, for the register view.
 */
export type AssetView = { id: string, class_id: string, name: string, cost: Money, residual: Money, acquired: string, settings: DepreciationSettings, rate_source: RateSource, accounts: AssetAccounts, opening: OpeningBalance | null, disposal: Disposal | null, 
/**
 * Held in a finalised year, so cost, dates and the brought-forward balance are fixed.
 */
fixed: boolean, };
