// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";

/**
 * One asset's movements in one client-year, in cents. Accumulated depreciation is positive.
 */
export type AssetYear = { opening_cost: Money, additions: Money, disposals: Money, closing_cost: Money, opening_accumulated: Money, depreciation: Money, disposal_accumulated: Money, closing_accumulated: Money, 
/**
 * Proceeds less book value at disposal; only in the year of disposal.
 */
gain: Money | null, };
