// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssetError = { "code": "bad_rate", rate_bp: number, } | { "code": "bad_life", months: number, } | { "code": "cost_not_positive" } | { "code": "bad_residual" } | { "code": "disposed_before_acquired" } | { "code": "negative_proceeds" } | { "code": "bad_opening_accumulated" } | { "code": "opening_not_after_acquired" } | { "code": "needs_opening_balance" } | { "code": "opening_not_year_start", date: string, };
