// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a year's books come from. Never both: that would double-count (CLAUDE.md).
 */
export type BooksSource = "tb_import" | "bank_coding";
