// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Change = { seq: number, kind: string, client_id: string | null, client_year_id: string | null, at: string, };
