// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { AccountType } from "./AccountType";

/**
 * A client's chart of accounts, kept sorted by code.
 */
export type Chart = Array<{ code: AccountCode, name: string, account_type: AccountType, active: boolean, }>;
