// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAccounts } from "./AssetAccounts";
import type { AssetClassView } from "./AssetClassView";
import type { DepreciationSettings } from "./DepreciationSettings";
import type { ResolvedClass } from "./ResolvedClass";

/**
 * A practice class as one client sees it.
 */
export type ClientClassView = { class: AssetClassView, override_settings: DepreciationSettings | null, override_accounts: AssetAccounts | null, resolved: ResolvedClass, };
