// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One client's financial year. First and last years may be shorter or longer than 12 months.
 */
export type ClientYear = { start: string, end: string, };
