// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { YearSummary } from "./YearSummary";

export type ClientDetail = { id: string, name: string, entity_type: string, retained_earnings: AccountCode, rounding_priority: Array<AccountCode>, 
/**
 * Earliest first.
 */
years: Array<YearSummary>, };
