// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { AccountCode } from "./AccountCode";
import type { JournalLine } from "./JournalLine";
import type { Mapping } from "./Mapping";
import type { Role } from "./Role";
import type { TbLine } from "./TbLine";
import type { Template } from "./Template";

/**
 * Every change to practice or client data (CLAUDE.md hard rule 6).
 */
export type Command = { "kind": "initialise", "payload": { practice_name: string, username: string, display_name: string, password: string, } } | { "kind": "create_user", "payload": { username: string, display_name: string, password: string, role: Role, } } | { "kind": "create_master_chart", "payload": { entity_type: string, name: string, accounts: Array<Account>, } } | { "kind": "create_template", "payload": { entity_type: string, name: string, body: Template, } } | { "kind": "revise_template", "payload": { template_id: string, body: Template, } } | { "kind": "create_mapping", "payload": { template_id: string, name: string, body: Mapping, } } | { "kind": "revise_mapping", "payload": { mapping_id: string, body: Mapping, } } | { "kind": "create_client", "payload": { name: string, entity_type: string, retained_earnings: AccountCode, rounding_priority: Array<AccountCode>, } } | { "kind": "add_account", "payload": { client_id: string, account: Account, } } | { "kind": "rename_account", "payload": { client_id: string, code: AccountCode, name: string, } } | { "kind": "set_account_active", "payload": { client_id: string, code: AccountCode, active: boolean, } } | { "kind": "set_rounding_priority", "payload": { client_id: string, rounding_priority: Array<AccountCode>, } } | { "kind": "create_client_year", "payload": { client_id: string, start: string, end: string, mapping_id?: string, } } | { "kind": "post_journal", "payload": { client_year_id: string, date: string, narration: string, lines: Array<JournalLine>, } } | { "kind": "import_tb", "payload": { client_year_id: string, rows: Array<TbLine>, } } | { "kind": "reverse_journal", "payload": { journal_id: string, date?: string, narration?: string, } };
