// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the prior-year column came from.
 */
export type Comparatives = "none" | "finalised" | "unfinalised";
