// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the posted asset journals match the register.
 */
export type DepreciationStatus = "current" | "stale" | "finalised";
