// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisposalYear } from "./DisposalYear";
import type { Method } from "./Method";
import type { PartYear } from "./PartYear";

/**
 * A method with its conventions: what an asset class sets as a default and what an asset
 * carries once created.
 */
export type DepreciationSettings = { method: Method, part_year: PartYear, disposal_year: DisposalYear, };
