// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the year of disposal is treated.
 */
export type DisposalYear = "none" | "to_disposal_date";
