// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { Money } from "./Money";

export type Disposal = { date: string, proceeds: Money, 
/**
 * The account debited with the proceeds.
 */
proceeds_account: AccountCode, };
