// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineKey } from "./LineKey";

/**
 * Two rows whose shown amounts must agree after rounding, such as net assets and total equity.
 */
export type EqualityCheck = { left: LineKey, right: LineKey, };
