// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of `GET /api/health`.
 */
export type Health = { status: string, version: string, };
