// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { Money } from "./Money";

/**
 * One line of a journal. Debits are positive and credits negative.
 */
export type JournalLine = { account: AccountCode, amount: Money, };
