// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JournalKind } from "./JournalKind";
import type { JournalLine } from "./JournalLine";

export type JournalView = { id: string, kind: JournalKind, date: string, narration: string, lines: Array<JournalLine>, reverses_journal_id: string | null, 
/**
 * The journal that reverses this one, if any.
 */
reversed_by: string | null, posted_seq: number, };
