// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { Money } from "./Money";

export type JournalError = { "code": "too_few_lines" } | { "code": "unbalanced", difference: Money, } | { "code": "unknown_account", line: number, account: AccountCode, } | { "code": "inactive_account", line: number, account: AccountCode, } | { "code": "outside_year", date: string, start: string, end: string, };
