// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stable key for a template row, such as `revenue` or `total_equity`. Lowercase ASCII letters,
 * digits, `_`, `-` and `.`. Mappings and ReportDocs refer to rows by key.
 */
export type LineKey = string;
