// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MappingRange } from "./MappingRange";

/**
 * The ranges that place accounts on a template's lines. Versions are tracked by the store; a
 * finalised year pins the version it used.
 */
export type Mapping = { ranges: Array<MappingRange>, };
