// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { LineKey } from "./LineKey";

/**
 * An inclusive range of account codes mapped to one template line.
 *
 * `to` also covers its own sub-accounts, so `200`–`299` includes `299.05`. See `docs/domain.md`.
 */
export type MappingRange = { from: AccountCode, to: AccountCode, line: LineKey, };
