// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { LineKey } from "./LineKey";

export type MappingError = { "code": "reversed_range", from: AccountCode, to: AccountCode, } | { "code": "unknown_line", from: AccountCode, to: AccountCode, line: LineKey, } | { "code": "overlap", first_from: AccountCode, first_to: AccountCode, second_from: AccountCode, second_to: AccountCode, } | { "code": "unmapped", account: AccountCode, };
