// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * The logged-in user, as the UI sees them.
 */
export type Me = { id: string, username: string, display_name: string, role: Role, };
