// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlBasis } from "./SlBasis";

/**
 * How an asset is depreciated.
 */
export type Method = { "kind": "dv", rate_bp: number, } | { "kind": "sl", basis: SlBasis, } | { "kind": "none" };
