// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineKey } from "./LineKey";
import type { Presentation } from "./Presentation";

/**
 * A row in a statement.
 */
export type Node = { "kind": "group", key: LineKey, label: string, presentation: Presentation, children: Array<Node>, total_label: string | null, 
/**
 * Set on key totals that rounding must keep equal to their exact total, rounded. Lower
 * numbers win when protected totals conflict. See `docs/domain.md`.
 */
protect: number | null, } | { "kind": "line", key: LineKey, label: string, presentation: Presentation, } | { "kind": "total", key: LineKey, label: string, presentation: Presentation, of: Array<LineKey>, protect: number | null, } | { "kind": "link", key: LineKey, label: string, presentation: Presentation, from: LineKey, };
