// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";

/**
 * Accumulated depreciation brought forward at the start of a client-year, for an asset acquired
 * before the register's first year.
 */
export type OpeningBalance = { 
/**
 * The start of the client-year the register begins tracking the asset.
 */
date: string, accumulated: Money, };
