// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the year of acquisition is prorated.
 */
export type PartYear = { "kind": "months_held", count_acquisition_month: boolean, } | { "kind": "daily" } | { "kind": "full_year" };
