// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MappingSummary } from "./MappingSummary";
import type { MasterChartView } from "./MasterChartView";
import type { TemplateSummary } from "./TemplateSummary";

/**
 * The practice's defaults, for choosing an entity type, chart accounts and mapping when
 * setting up a client.
 */
export type PracticeView = { name: string, 
/**
 * By entity type.
 */
master_charts: Array<MasterChartView>, 
/**
 * By entity type, then oldest first.
 */
templates: Array<TemplateSummary>, 
/**
 * By entity type, then oldest first.
 */
mappings: Array<MappingSummary>, };
