// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a row's ledger-sign amount is shown.
 */
export type Presentation = "debit_positive" | "credit_positive";
