// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { Money } from "./Money";

/**
 * The register against the ledger for one account.
 */
export type ReconciliationLine = { account: AccountCode, 
/**
 * What the register says the balance should be (debit positive).
 */
register: Money, ledger: Money, };
