// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineKey } from "./LineKey";
import type { RowAccount } from "./RowAccount";
import type { RowRounding } from "./RowRounding";
import type { RowStyle } from "./RowStyle";

/**
 * One row as shown. Amounts are whole dollars in presentation sign.
 */
export type ReportRow = { key: LineKey, style: RowStyle, depth: number, label: string, current: number | null, prior: number | null, 
/**
 * For lines: the accounts behind the line, for drill-down.
 */
accounts: Array<RowAccount>, 
/**
 * For lines that absorbed rounding: the dollars added, per column (zero if none).
 */
rounding: RowRounding | null, };
