// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetSchedule } from "./AssetSchedule";
import type { Comparatives } from "./Comparatives";
import type { Period } from "./Period";
import type { ReportStatement } from "./ReportStatement";
import type { ReportWarning } from "./ReportWarning";

/**
 * The built statements. Holds no ids, timestamps or hash maps, so its JSON is byte-stable.
 */
export type ReportDoc = { template: string, current_period: Period, prior_period: Period | null, comparatives: Comparatives, statements: Array<ReportStatement>, 
/**
 * The fixed asset schedule, when the client has an asset register. Built separately by
 * [`crate::depreciation::build_asset_schedule`] and attached by the caller.
 */
asset_schedule?: AssetSchedule, warnings: Array<ReportWarning>, };
