// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineKey } from "./LineKey";
import type { ReportRow } from "./ReportRow";

export type ReportStatement = { key: LineKey, title: string, rows: Array<ReportRow>, };
