// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { LineKey } from "./LineKey";

export type ReportWarning = { "code": "rounding_fallback", column: Column, row: LineKey, line: LineKey, } | { "code": "cannot_round", column: Column, row: LineKey, difference: number, } | { "code": "check_failed", column: Column, left: LineKey, right: LineKey, left_amount: number, right_amount: number, };
