// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAccounts } from "./AssetAccounts";
import type { DepreciationSettings } from "./DepreciationSettings";
import type { RateSource } from "./RateSource";

/**
 * A class's defaults for one client: the client's override where there is one, else the
 * practice's.
 */
export type ResolvedClass = { settings: DepreciationSettings, 
/**
 * `practice` or `client`.
 */
source: RateSource, accounts: AssetAccounts, };
