// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { Money } from "./Money";

/**
 * The imported retained earnings differ from the figure rolled forward from last year. That
 * usually means last year's adjustments were never posted in the client's own books.
 */
export type RetainedEarningsGap = { account: AccountCode, imported: Money, rolled_forward: Money, 
/**
 * `imported − rolled_forward`.
 */
difference: Money, };
