// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { Money } from "./Money";

/**
 * An account behind a line, with its real balances in cents, in the line's presentation sign.
 */
export type RowAccount = { code: AccountCode, current: Money, prior: Money, };
