// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScheduleRowKey } from "./ScheduleRowKey";
import type { ScheduleRowStyle } from "./ScheduleRowStyle";

/**
 * Disposals and depreciation on disposals are negative, so each part foots downwards.
 * A loss on disposal is negative.
 */
export type ScheduleRow = { key: ScheduleRowKey, style: ScheduleRowStyle, label: string, current: number | null, prior: number | null, };
