// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScheduleRowKey = "opening_cost" | "additions" | "disposals" | "closing_cost" | "opening_accumulated" | "depreciation" | "disposal_accumulated" | "closing_accumulated" | "book_value" | "gain";
