// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScheduleRow } from "./ScheduleRow";

export type ScheduleBlock = { 
/**
 * The class's code, or `None` for the total block.
 */
class: string | null, title: string, rows: Array<ScheduleRow>, };
