// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a straight-line charge is based on.
 */
export type SlBasis = { "kind": "rate", rate_bp: number, } | { "kind": "life", months: number, };
