// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineKey } from "./LineKey";
import type { Node } from "./Node";

/**
 * One statement, such as the statement of financial performance.
 */
export type Statement = { key: LineKey, title: string, body: Array<Node>, };
