// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Change } from "./Change";

/**
 * Changes after `after`, oldest first. If `changes` is full (`limit` long), ask again from
 * `last_seq`.
 */
export type SyncFeed = { changes: Array<Change>, 
/**
 * The newest `seq` in `changes`, or `after` if there were none.
 */
last_seq: number, };
