// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { Money } from "./Money";

export type TbCsvError = { "code": "unreadable", message: string, } | { "code": "unknown_layout", header: Array<string>, } | { "code": "bad_code", row: number, value: string, message: string, } | { "code": "bad_amount", row: number, column: string, value: string, message: string, } | { "code": "debit_and_credit", row: number, } | { "code": "duplicate_code", row: number, account: AccountCode, first_row: number, } | { "code": "unbalanced", difference: Money, } | { "code": "empty" };
