// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { Money } from "./Money";

/**
 * Something that stops the import.
 */
export type TbImportProblem = { "code": "unknown_account", account: AccountCode, } | { "code": "inactive_account", account: AccountCode, } | { "code": "duplicate_account", account: AccountCode, } | { "code": "unbalanced", difference: Money, } | { "code": "books_from_bank_coding" } | { "code": "year_finalised" };
