// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JournalLine } from "./JournalLine";
import type { RetainedEarningsGap } from "./RetainedEarningsGap";
import type { TbCsvError } from "./TbCsvError";
import type { TbImportProblem } from "./TbImportProblem";
import type { TbRow } from "./TbRow";

/**
 * The response to `POST /api/years/{id}/tb-import/preview`.
 */
export type TbImportPreview = { 
/**
 * The file's rows, to show for checking. Empty if the file couldn't be read.
 */
rows: Array<TbRow>, 
/**
 * Problems with the file itself. If there are any, nothing else is worked out.
 */
file_errors: Array<TbCsvError>, 
/**
 * Problems that stop the import.
 */
problems: Array<TbImportProblem>, 
/**
 * The journal the import would post.
 */
lines: Array<JournalLine>, 
/**
 * The TB-import journal this would replace, if there is one.
 */
replaces_journal_id: string | null, 
/**
 * Importing would change nothing.
 */
unchanged: boolean, retained_earnings_gap: RetainedEarningsGap | null, };
