// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { Money } from "./Money";

export type TbLine = { account: AccountCode, balance: Money, };
