// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { Money } from "./Money";

/**
 * One account's balance from the file. `row` is the file's line number, counting the header
 * as row 1, for messages.
 */
export type TbRow = { row: number, code: AccountCode, 
/**
 * The name in the file. It's shown for checking, never used to match accounts.
 */
name: string, balance: Money, };
