// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EqualityCheck } from "./EqualityCheck";
import type { Statement } from "./Statement";

/**
 * A set of statements for one entity type.
 */
export type Template = { name: string, statements: Array<Statement>, checks: Array<EqualityCheck>, };
