// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCode } from "./AccountCode";
import type { Money } from "./Money";

/**
 * Account balances, keyed and ordered by account code. Zero balances are left out, so two trial
 * balances with the same non-zero balances are equal.
 */
export type TrialBalance = Array<{ account: AccountCode, balance: Money, }>;
