// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * A user as the practice settings page shows them. Never the password hash.
 */
export type UserView = { id: string, username: string, display_name: string, role: Role, active: boolean, };
