// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TbLine } from "./TbLine";

/**
 * A year's trial balance: opening balances (rolled forward, never posted) and closing
 * balances, by account code. Accounts with nil balances are left out.
 */
export type YearTrialBalance = { opening: Array<TbLine>, closing: Array<TbLine>, };
