// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BooksSource } from "./BooksSource";
import type { YearStatus } from "./YearStatus";

export type YearSummary = { id: string, client_id: string, start: string, end: string, status: YearStatus, books_source: BooksSource | null, };
