// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetYearView } from "./AssetYearView";
import type { DepreciationStatus } from "./DepreciationStatus";
import type { Journal } from "./Journal";
import type { ReconciliationLine } from "./ReconciliationLine";

/**
 * `GET /api/years/{id}/assets`
 */
export type YearAssets = { 
/**
 * Every asset in the register. Those not held in the year have nil movements.
 */
assets: Array<AssetYearView>, status: DepreciationStatus, 
/**
 * Earlier open years whose asset journals are stale.
 */
stale_earlier_years: Array<string>, 
/**
 * What the depreciation run would post in this year.
 */
journals: Array<Journal>, 
/**
 * The register against the ledger at the end of the year.
 */
reconciliation: Array<ReconciliationLine>, };
